CREATE TABLE REGISTERTABLE (
    EMP_ID NUMBER(3) NOT NULL,
    EMP_NAME VARCHAR2(15) NOT NULL,
    USERTYPE VARCHAR2(15) NOT NULL,
    USERNAME VARCHAR2(15) NOT NULL,
    EMP_PASSWORD VARCHAR2(15) NOT NULL,
    GENDER VARCHAR2(15) NOT NULL,
    MOBILE NUMBER(10) NOT NULL,
    EMAIL VARCHAR2(15) NOT NULL,
    DATEOFBIRTH DATE NOT NULL,
    ADDRESS VARCHAR2(15) NOT NULL,
    CITY VARCHAR2(15) NOT NULL,
    EMP_STATE VARCHAR2(15) NOT NULL
);

ALTER TABLE REGISTERTABLE
ADD(
    CONSTRAINT EMP_ID_PK PRIMARY KEY (EMP_ID)
);

CREATE SEQUENCE REGISTERTABLE_SEQUENCE;

CREATE OR REPLACE TRIGGER REGISTERTABLE_INSERT
BEFORE INSERT ON REGISTERTABLE
FOR EACH ROW
BEGIN
    SELECT REGISTERTABLE_SEQUENCE.NEXTVAL
    INTO :NEW.EMP_ID
    FROM DUAL;
END;