CREATE OR REPLACE PROCEDURE FORGET_PASSWORD(
    E_EMAIL IN REGISTERTABLE.EMAIL%TYPE,
    E_DISPLAY OUT SYS_REFCURSOR
)
IS
BEGIN
OPEN E_DISPLAY FOR SELECT USERNAME,EMP_PASSWORD FROM REGISTERTABLE WHERE EMAIL = E_EMAIL;
COMMIT;
END;