CREATE OR REPLACE PROCEDURE GET_LEAVE (
	
	E_ID IN LEAVETABLE.EMP_ID%TYPE,
	E_DISPLAY OUT SYS_REFCURSOR
)
AS
BEGIN
OPEN E_DISPLAY FOR SELECT LEAVE_TYPE,LEAVE_START,LEAVE_END,LEAVE_DAYS,LEAVE_DESCRIPTION,LEAVE_STATUS,LEAVE_BALANCE
FROM LEAVETABLE WHERE EMP_ID = E_ID;
COMMIT;
END;
/