CREATE OR REPLACE PROCEDURE GET_EMPLOYEEDETAIL(

    E_USERNAME IN REGISTERTABLE.USERNAME%TYPE,
    E_DISPLAY OUT SYS_REFCURSOR
)
AS
BEGIN
OPEN E_DISPLAY FOR SELECT EMP_ID,EMP_NAME,EMAIL,MOBILE,GENDER,DATEOFBIRTH,ADDRESS,CITY,EMP_STATE FROM REGISTERTABLE WHERE USERNAME = E_USERNAME;
COMMIT;
END;