create or replace PROCEDURE INSERT_LEAVETABLE(
    
    E_ID IN LEAVETABLE.EMP_ID%TYPE,
    E_LEAVETYPE IN LEAVETABLE.LEAVE_TYPE%TYPE,
    E_STARTDATE IN LEAVETABLE.LEAVE_START%TYPE,
    E_ENDDATE IN LEAVETABLE.LEAVE_END%TYPE,
    E_LEAVEDURATION IN LEAVETABLE.LEAVE_DAYS%TYPE,
    E_LEAVEDESCRIPTION IN LEAVETABLE.LEAVE_DESCRIPTION%TYPE,
    E_LEAVESTATUS IN LEAVETABLE.LEAVE_STATUS%TYPE,
    E_LEAVEBALANCE IN LEAVETABLE.LEAVE_BALANCE%TYPE
)
IS
V_COUNT NUMBER := 0;
BEGIN

    SELECT COUNT(1) INTO V_COUNT FROM LEAVETABLE WHERE LEAVE_START = E_STARTDATE AND EMP_ID = E_ID;

    IF V_COUNT = 0 THEN INSERT INTO LEAVETABLE (EMP_ID,LEAVE_TYPE,LEAVE_START,LEAVE_END,LEAVE_DAYS,LEAVE_DESCRIPTION,LEAVE_STATUS,LEAVE_BALANCE)
    VALUES (E_ID,E_LEAVETYPE,E_STARTDATE,E_ENDDATE,E_LEAVEDURATION,E_LEAVEDESCRIPTION,E_LEAVESTATUS,E_LEAVEBALANCE);

COMMIT;
END IF;
END;