CREATE OR REPLACE PROCEDURE INSERTUSER(
	   P_NAME IN SAMPLE.NAME%TYPE,
	   P_MOBILE IN SAMPLE.MOBILE%TYPE,
	   P_EMAIL IN SAMPLE.EMAIL%TYPE)
IS
BEGIN

  INSERT INTO DBUSER ("NAME", "MOBILE", "EMAIL")
  VALUES (P_NAME, P_MOBIEL,P_EMAIL);

  COMMIT;

END;
/

