CREATE TABLE MASTERTABLE 
(
    KEY VARCHAR2(15) NOT NULL,
    VALUE VARCHAR2(15) NOT NULL
);

INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeGender','Male');
INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeGender','Female');
INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeLeave','Half Leave');
INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeLeave','Full leave');
INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeState','Gujarat');
INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeState','MadhyaPradesh');
INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeState','Maharastra');
INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeState','Rajasthan');
INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeCity','Rajkot');
INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeCity','Bhopal');
INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeCity','Mumbai');
INSERT INTO MASTERTABLE (KEY,VALUE) VALUES ('EmployeeCity','Kota');