CREATE OR REPLACE PROCEDURE INSERT_REGISTERTABLE(
    E_NAME IN REGISTERTABLE.EMP_NAME%TYPE,
    E_USERTYPE IN REGISTERTABLE.USERTYPE%TYPE,
    E_USERNAME IN REGISTERTABLE.USERNAME%TYPE,
    E_PASSWORD IN REGISTERTABLE.EMP_PASSWORD%TYPE,
    E_GENDER IN REGISTERTABLE.GENDER%TYPE,
    E_MOBILE IN REGISTERTABLE.MOBILE%TYPE,
    E_EMAIL IN REGISTERTABLE.EMAIL%TYPE,
    E_DATEOFBIRTH IN REGISTERTABLE.DATEOFBIRTH%TYPE,
    E_ADDRESS IN REGISTERTABLE.ADDRESS%TYPE,
    E_CITY IN REGISTERTABLE.CITY%TYPE,
    E_STATE IN REGISTERTABLE.EMP_STATE%TYPE
)
IS
BEGIN

    INSERT INTO REGISTERTABLE (EMP_NAME,USERTYPE,USERNAME,EMP_PASSWORD,GENDER,MOBILE,EMAIL,DATEOFBIRTH,ADDRESS,CITY,EMP_STATE)
    VALUES (E_NAME,E_USERTYPE,E_USERNAME,E_PASSWORD,E_GENDER,E_MOBILE,E_EMAIL,E_DATEOFBIRTH,E_ADDRESS,E_CITY,E_STATE);
    
COMMIT;
END;
/