CREATE OR REPLACE PROCEDURE UPDATE_LEAVESTATUS
(
	E_ID IN LEAVETABLE.EMP_ID%TYPE,
	E_STARTDATE IN LEAVETABLE.LEAVE_START%TYPE,
	E_LEAVESTATUS IN LEAVETABLE.LEAVE_STATUS%TYPE
)
IS
BEGIN
	UPDATE LEAVETABLE SET LEAVE_STATUS = E_LEAVESTATUS WHERE EMP_ID = E_ID AND LEAVE_START = E_STARTDATE;
COMMIT;
END;
/