CREATE OR REPLACE PROCEDURE UPDATE_PROFILE
(
    E_ID IN REGISTERTABLE.EMP_ID%TYPE,
    E_NAME IN REGISTERTABLE.EMP_NAME%TYPE,
    E_GENDER IN REGISTERTABLE.GENDER%TYPE,
    E_MOBILE IN REGISTERTABLE.MOBILE%TYPE,
    E_EMAIL IN REGISTERTABLE.EMAIL%TYPE,
    E_ADDRESS IN REGISTERTABLE.ADDRESS%TYPE,
    E_CITY IN REGISTERTABLE.CITY%TYPE,
    E_STATE IN REGISTERTABLE.EMP_STATE%TYPE
)
IS
BEGIN
	UPDATE REGISTERTABLE SET EMP_NAME = E_NAME,GENDER = E_GENDER,MOBILE = E_MOBILE,EMAIL = E_EMAIL,ADDRESS = E_ADDRESS,CITY = E_CITY,EMP_STATE = E_STATE WHERE EMP_ID = E_ID;
COMMIT;
END;
/